In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
file_path = '/content/Sales_data.txt'
df = pd.read_csv(file_path)
df

,Sale ID,Company,Contact,Contact Sex,Contact Age,Contact City,Contact State,Product Company,Product ID,Product Type,Sale Price,Our Cost,Shipping Cost,Profit,Lead Source,Sale Month,Sale Year
0,1,PNT Designs,Paul Thomas,M,43,Carnegie,OH,HP,M01-F0024,Desktop,479.99,315.50,21.1,143.39,Website,January,2018
1,2,Ace Manufacturing,Margo Simms,F,37,Larimer,WV,HP,GT13-0024,Desktop,1249.99,998.00,21.1,230.89,Flyer 4,January,2018
2,3,Sammie's,Sam Stine,M,26,Pittsburgh,PA,Dell,I3670,Desktop,649.99,510.25,21.1,118.64,Website,February,2018
3,4,One Moe Time,Moe Eggert,M,35,St. Clair,PA,Dell,I3593,Laptop,399.99,310.50,17.4,72.09,Website,March,2018
4,5,Get Going Gym,Jessica Elk,F,55,Pittsburgh,PA,HP,15M-ED,Laptop,699.99,584.50,17.4,98.09,Flyer 4,March,2018
5,6,ANX Trucking,Sally Struthers,F,45,St. Clair,PA,HP,GT13-0024,Desktop,1249.99,998.00,21.1,230.89,Flyer 2,April,2018
6,7,Samms Grooming,Michelle Samms,F,46,Carnegie,OH,ASUS,GA401IV,Laptop,1349.99,1152.25,17.4,180.34,Email,May,2018
7,8,Roberts Produce,Mick Roberts,M,23,Lawrenceville,OH,Apple,MY2J2LL,Tablet,999.99,845.00,8.3,146.69,Website,July,2018
8,9,Klondike Dairy,Ed Klondike,M,52,Carnegie,OH,Lenovo,81TC00,Laptop,649.99,510.25,17.4,122.34,Email,July,2018
9,10,Jones Manufacturing,Phil Jones,M,56,Larimer,WV,HP,M01-F0024,Desktop,479.99,315.50,21.1,143.39,Flyer 2,August,2018
10,11,James Cycles,Rick James,M,49,Pittsburgh,PA,ASUS,GA401IV,Laptop,1349.99,1152.25,17.4,180.34,Flyer 3,November,2018
11,12,Weight Stalkers,Sue Etna,F,54,Banksville,OH,HP,GT13-0024,Desktop,1249.99,998.00,21.1,230.89,Flyer 2,November,2018
12,13,Case Solutions,Jason Case,M,57,Pittsburgh,PA,Lenovo,81TC00,Laptop,649.99,510.25,17.4,122.34,Email,November,2018
13,14,Doug's House,Doug Johnson,M,51,Pittsburgh,PA,Dell,I3670,Desktop,649.99,510.25,21.1,118.64,Website,December,2018
14,15,Helms Manufacturing,Andy Sands,M,56,Lawrenceville,OH,Apple,MY2J2LL,Tablet,999.99,845.00,8.3,146.69,Flyer 1,December,2018
15,16,Collins Advertising,Kim Collins,F,49,Pittsburgh,PA,Dell,I3593,Laptop,399.99,310.50,17.4,72.09,Flyer 2,January,2019
16,17,Owens & Sons,Edna Sanders,F,46,Lawrenceville,OH,HP,15M-ED,Laptop,699.99,584.50,17.4,98.09,Email,February,2019
17,18,Samms Grooming,Michelle Samms,F,46,Banksville,NY,Apple,MY2J2LL,Tablet,999.99,845.00,8.3,146.69,Website,March,2019
18,19,Roberts Produce,Mick Roberts,M,23,Pittsburgh,PA,Dell,I3593,Laptop,399.99,310.50,17.4,72.09,Flyer 4,March,2019
19,20,ANX Trucking,Sally Struthers,F,45,Banksville,NY,Lenovo,81TC00,Laptop,649.99,510.25,17.4,122.34,Website,April,2019
20,21,Case Solutions,Jason Case,M,57,Pittsburgh,PA,HP,M01-F0024,Desktop,479.99,315.50,21.1,143.39,Flyer 4,May,2019
21,22,Doug's House,Doug Johnson,M,51,Pittsburgh,PA,ASUS,GA401IV,Laptop,1349.99,1152.25,17.4,180.34,Website,August,2019
22,23,PNT Designs,Paul Thomas,M,43,Carnegie,OH,Lenovo,81TC00,Laptop,649.99,510.25,17.4,122.34,Website,August,2019
23,24,Ace Manufacturing,Margo Simms,F,37,Larimer,WV,ASUS,Q526FA,Laptop,1049.99,889.50,17.4,143.09,Flyer 4,November,2019
24,25,Samms Grooming,Michelle Samms,F,46,Banksville,NY,Dell,I3670,Desktop,649.99,510.25,21.1,118.64,Flyer 2,November,2019
25,26,Roberts Produce,Mick Roberts,M,23,Pittsburgh,PA,ASUS,Q526FA,Laptop,1049.99,889.50,17.4,143.09,Email,November,2019
26,27,Klondike Dairy,Ed Klondike,M,52,Carnegie,OH,ASUS,Q526FA,Laptop,1049.99,889.50,17.4,143.09,Website,December,2019
27,28,One Moe Time,Moe Eggert,M,35,St. Clair,PA,HP,15M-ED,Laptop,699.99,584.50,17.4,98.09,Email,December,2019
28,29,Get Going Gym,Jessica Elk,F,55,Pittsburgh,PA,ASUS,GA401IV,Laptop,1349.99,1152.25,17.4,180.34,Flyer 2,December,2019
29,30,Jones Manufacturing,Phil Jones,M,56,Larimer,WV,HP,M01-F0024,Desktop,479.99,315.50,21.1,143.39,Flyer 2,January,2020
30,31,James Cycles,Rick James,M,49,Pittsburgh,PA,ASUS,GA401IV,Laptop,1349.99,1152.25,17.4,180.34,Flyer 1,January,2020
31,32,Weight Stalkers,Sue Etna,F,54,Banksville,OH,HP,GT13-0024,Desktop,1249.99,998.00,21.1,230.89,Flyer 2,February,2020
32,33,Collins Advertising,Kim Collins,F,49,Pittsburgh,PA,Dell,I3593,Laptop,399.99,310.50,17.4,72.09,Flyer 2,March,2020
33,34,Owens & Sons,Edna Sanders,F,46,Lawrenceville,OH,HP,15M-ED,Laptop,699.99,584.50,17.4,98.09,Email,March,2020
34,35,Samms Grooming,Michelle Samms,F,46,Banksville,NY,Apple,MY2J2LL,Tablet,999.99,845.00,8.3,146.69,Website,April,2020
35,36,ANX Trucking,Sally Struthers,F,45,Banksville,NY,Lenovo,81TC00,Laptop,649.99,510.25,17.4,122.34,Website,April,2020
36,37,Case Solutions,Jason Case,M,57,Pittsburgh,PA,HP,M01-F0024,Desktop,479.99,315.50,21.1,143.39,Flyer 4,April,2020
37,38,Doug's House,Doug Johnson,M,51,Pittsburgh,PA,ASUS,GA401IV,Laptop,1349.99,1152.25,17.4,180.34,Website,May,2020
38,39,One Moe Time,Moe Eggert,M,35,St. Clair,PA,Dell,I3593,Laptop,399.99,310.50,17.4,72.09,Website,May,2020

In [3]:
df.describe()

,Sale ID,Contact Age,Sale Price,Our Cost,Shipping Cost,Profit,Sale Year
count,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000
mean,20.000000,45.666667,837.169487,679.589744,17.605128,139.974615,2018.871795
std,11.401754,9.820315,342.229138,307.670986,3.605110,44.746575,0.800641
min,1.000000,23.000000,399.990000,310.500000,8.300000,72.090000,2018.000000
25%,10.500000,43.000000,564.990000,412.875000,17.400000,118.640000,2018.000000
50%,20.000000,46.000000,699.990000,584.500000,17.400000,143.090000,2019.000000
75%,29.500000,53.000000,1149.990000,943.750000,21.100000,163.515000,2019.500000
max,39.000000,57.000000,1349.990000,1152.250000,21.100000,230.890000,2020.000000

# 1

In [4]:
female = df[df['Contact Sex'] == 'F']
female_count = female.groupby(female['Contact Sex']).count()
female_count

,Sale ID,Company,Contact,Contact Age,Contact City,Contact State,Product Company,Product ID,Product Type,Sale Price,Our Cost,Shipping Cost,Profit,Lead Source,Sale Month,Sale Year
Contact Sex,,,,,,,,,,,,,,,,
F,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17

In [5]:
male = df[df['Contact Sex'] == 'M']
male_count = male.groupby(male['Contact Sex']).count()
male_count

,Sale ID,Company,Contact,Contact Age,Contact City,Contact State,Product Company,Product ID,Product Type,Sale Price,Our Cost,Shipping Cost,Profit,Lead Source,Sale Month,Sale Year
Contact Sex,,,,,,,,,,,,,,,,
M,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22

Based on the female_count and male_count we can say that males are the most frequent buyers. You can see that the amount of females that made a perchase is 17 while the amount of buyers for males are 22.

# 2

Based on question 1, we can say that males should be targeted if the business is cash-constrained, since males were the more frequent buyers.

# 3

We can say that males should be targeted if consumers are cash-constrained, since they are more likely to purchase technololgy.

# 4

In [6]:
age_group = df.groupby('Contact Age')['Profit'].sum().sort_values(ascending=False)
print(age_group)

Contact Age
46    788.54
49    504.86
51    479.32
45    475.57
54    461.78
56    433.47
57    409.12
37    373.98
23    361.87
55    278.43
43    265.73
52    265.43
35    242.27
26    118.64
Name: Profit, dtype: float64

After grouping by age, we can say that our target age to maximize profit should be 46, since the amount of purchases was higher for those who were 46 years old.

# 5

In [7]:
product = df.groupby('Product Type')['Profit'].sum().sort_values(ascending=False)
product

Product Type
Laptop     2875.82
Desktop    1996.43
Tablet      586.76
Name: Profit, dtype: float64

After grouping the product types, we can see that laptops should be featured more, since more laptops are being sold compared to desktops and tablets.

# 6

In [8]:
lead_source = df.groupby('Lead Source')['Profit'].sum().sort_values(ascending=False)
lead_source

Lead Source
Website    1835.71
Flyer 2    1422.61
Email       862.38
Flyer 4     830.94
Flyer 1     327.03
Flyer 3     180.34
Name: Profit, dtype: float64

The lead source that has worked in the past has been the website, since we can see that there was more profit coming in from that lead source compared to the other types.

# 7

In [9]:
email_marketing = df[df['Lead Source'] == 'Email'].groupby('Sale Year')['Profit'].sum().sort_values(ascending=False)
email_marketing

Sale Year
2018    425.02
2019    339.27
2020     98.09
Name: Profit, dtype: float64

The best time to do email marketing was in the year 2018, since more profit was made during that time compared to other years.